import json
from openai import OpenAI
from google import genai
import streamlit as st
import streamlit.components.v1 as components
import os
from reportlab.platypus import SimpleDocTemplate, Paragraph
from reportlab.lib.styles import getSampleStyleSheet
import io
import re
from dotenv import load_dotenv

load_dotenv()

API_KEY=os.getenv("API_KEY")
styles = getSampleStyleSheet()
with open("optimization_results.json","r") as f:
    classical_optimization_results=json.load(f)

with open("quantum_optimization_results.json","r") as f:
    quantum_optimization_results=json.load(f)

from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.colors import HexColor
from reportlab.platypus import Spacer
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import ParagraphStyle
from reportlab.platypus import (
    Table,
    TableStyle,
    PageBreak,
    ListFlowable,
    ListItem
)

import random

from reportlab.lib import colors

def create_table(data):

    table = Table(data, colWidths=[220, 250])

    table.setStyle(TableStyle([

        ("BACKGROUND",(0,0),(-1,0),colors.HexColor("#1f4e79")),
        ("TEXTCOLOR",(0,0),(-1,0),colors.white),

        ("FONTNAME",(0,0),(-1,0),"Helvetica-Bold"),

        ("BACKGROUND",(0,1),(-1,-1),colors.whitesmoke),

        ("GRID",(0,0),(-1,-1),0.5,colors.grey),

        ("BOTTOMPADDING",(0,0),(-1,0),8),

        ("TOPPADDING",(0,1),(-1,-1),6),

        ("FONTNAME",(0,1),(-1,-1),"Helvetica")

    ]))

    return table

title_style = ParagraphStyle(
    "TitleStyle",
    parent=styles["Title"],
    fontName="Helvetica-Bold",
    fontSize=22,
    alignment=TA_CENTER,
    textColor=HexColor("#1f4e79"),
    spaceAfter=20,
)

heading_style = ParagraphStyle(
    "HeadingStyle",
    parent=styles["Heading2"],
    fontName="Helvetica-Bold",
    fontSize=16,
    textColor=HexColor("#003366"),
    spaceBefore=12,
    spaceAfter=8,
)

body_style = ParagraphStyle(
    "BodyStyle",
    parent=styles["BodyText"],
    fontName="Helvetica",
    fontSize=11,
    leading=18,
)

# Footer styles
footer_heading = ParagraphStyle(
    "FooterHeading",
    parent=heading_style,
    alignment=TA_CENTER,
    fontName="Helvetica-Bold",
    fontSize=16,
    spaceBefore=25,
    spaceAfter=10,
)

footer_body = ParagraphStyle(
    "FooterBody",
    parent=body_style,
    alignment=TA_CENTER,
    fontSize=12,
    leading=20,
)

client = genai.Client(api_key=API_KEY)


def generate_pdf(summary, classical_results, quantum_results):
    clean_summary = re.sub(r'^#{1,6}\s*', '', summary, flags=re.MULTILINE)
    clean_summary = clean_summary.replace("\n", "<br/>")

    buffer = io.BytesIO()

    doc = SimpleDocTemplate(buffer)

    styles = getSampleStyleSheet()

    elements = []

    elements.append(
        Paragraph(
            "MULTI-ASSET PORTFOLIO OPTIMIZATION REPORT",
            title_style
        )
    )

    elements.append(Spacer(1,40))

    elements.append(
        Paragraph(
            "Generated by AI Portfolio Copilot",
            footer_body
        )
    )

    elements.append(
        Paragraph(
            "WISER Vanguard Quantum Challenge",
            footer_body
        )
    )

    elements.append(PageBreak())
    

    elements.append(
        Paragraph("<br/><b>AI Copilot Summary</b>",
                  heading_style)
    )

    elements.append(
    Paragraph(
        "Overall Summary",
        heading_style
        )
    )

    summary_lines = [
        line.strip()
        for line in clean_summary.split("\n")
        if line.strip()
    ]

    bullet_list = ListFlowable(

        [
            ListItem(
                Paragraph(line, body_style)
            )
            for line in summary_lines
        ],

        bulletType='bullet'

    )

    elements.append(bullet_list)

    elements.append(
    Paragraph(
        "Classical Portfolio",
        heading_style
        )
    )

    classical_table = [

        ["Metric","Value"],

        ["Portfolio Return",
        classical_results["portfolio_return"]],

        ["Portfolio Volatility",
        classical_results["portfolio_volatility"]],

        ["Execution Time",
        f"{classical_results['execution_time']:.3f} sec"],

        ["Transaction Cost",
        f"₹{classical_results['total_transaction_cost']:.2f}"],

        ["Cash Remaining",
        f"₹{classical_results['cash_remaining']:.2f}"]

    ]

    elements.append(
        create_table(classical_table)
    )

    elements.append(
    Paragraph(
        "Quantum Portfolio",
        heading_style
        )
    )

    quantum_table = [

        ["Metric","Value"],

        ["Portfolio Return",
        quantum_results["quantum_portfolio_return"]],

        ["Portfolio Risk",
        quantum_results["quantum_portfolio_risk"]],

        ["Execution Time",
        f"{quantum_results['execution_time']:.3f} sec"],

        ["Transaction Cost",
        f"₹{quantum_results['total_transaction_cost']:.2f}"]

    ]

    elements.append(
        create_table(quantum_table)
    )
    
    comparison = [

        ["Metric","Classical","Quantum"],

        ["Return",
        classical_results["portfolio_return"],
        quantum_results["quantum_portfolio_return"]],

        ["Risk",
        classical_results["portfolio_volatility"],
        quantum_results["quantum_portfolio_risk"]],

        ["Execution Time",
        classical_results["execution_time"],
        quantum_results["execution_time"]],

        ["Transaction Cost",
        classical_results["total_transaction_cost"],
        quantum_results["total_transaction_cost"]],
    ]

    comparison_table = Table(
        comparison,
        colWidths=[170, 140, 140]   # Adjust widths as needed
    )

    comparison_table.setStyle(TableStyle([

        # Header
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1f4e79")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
        ("FONTSIZE", (0, 0), (-1, 0), 12),

        # Body
        ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
        ("FONTNAME", (0, 1), (-1, -1), "Helvetica"),
        ("FONTSIZE", (0, 1), (-1, -1), 10),

        # Alignment
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),

        # Grid
        ("GRID", (0, 0), (-1, -1), 0.75, colors.grey),

        # Padding
        ("BOTTOMPADDING", (0, 0), (-1, 0), 10),
        ("TOPPADDING", (0, 1), (-1, -1), 8),
        ("BOTTOMPADDING", (0, 1), (-1, -1), 8),
    ]))

    elements.append(
        Paragraph("Classical vs Quantum Comparison", heading_style)
    )

    elements.append(comparison_table)


    objective = [

        ["Component","Value"],

        ["Expected Return",
        quantum_results["binary_breakdown"]["expected_return"]],

        ["Risk Penalty",
        quantum_results["binary_breakdown"]["risk_penalty"]],

        ["Liquidity Reward",
        quantum_results["binary_breakdown"]["liquidity_reward"]],

        ["Transaction Cost",
        quantum_results["binary_breakdown"]["transaction_cost"]],

        ["Diversification",
        quantum_results["binary_breakdown"]["diversification_penalty"]]

        ]

    elements.append(
            create_table(objective)
        )

    elements.append(PageBreak())
    elements.append(Spacer(1, 30))

    elements.append(
        Paragraph(
            "Project Developed By",
            footer_heading,
        )
    )

    elements.append(
        Paragraph(
            "<b>Sri Sai Harshavardhan Prabhamdhamkam</b>",
            footer_body,
        )
    )

    elements.append(
            Paragraph(
                "<b>Jayadeep Potluri</b>",
                footer_body,
        )
    )

    elements.append(
        Paragraph(
            "Quantum Computing & Software Developer",
            footer_body,
        )
    )

    elements.append(
        Paragraph(
            "Multi-Asset Portfolio Optimization",
            footer_body,
        )
    )

    elements.append(
        Paragraph(
            "WISER Vanguard Quantum Challenge 2026",
            footer_body,
        )
    )

    elements.append(Spacer(1, 15))

    elements.append(
        Paragraph(
            "<b>Technologies Used</b>",
            footer_heading,
        )
    )

    elements.append(
        Paragraph(
            "Python | Qiskit | QAOA | SciPy | CPLEX | Streamlit | Plotly | Gemini AI",
            footer_body,
        )
    )

    elements.append(Spacer(1, 15))

    elements.append(
        Paragraph(
            "Thank you for reviewing this project.",
            footer_body,
        )
    )

    doc.build(elements)

    pdf = buffer.getvalue()

    buffer.close()

    return pdf

def portfolio_copilot(question,classical_optimization_results,quantum_optimization_results):
    """
    AI Portfolio Chatbot

    Parameters
    ----------
    question : str
        User's question.

    classical_results : dict
        Classical optimizer output.

    quantum_results : dict
        Quantum optimizer output.

    Returns
    -------
    str
        AI-generated answer.
    """

    system_prompt =""" 
    You are an AI Financial Portfolio Assistant.

    Your responsibilities:
    - Analyze only the provided Classical and Quantum portfolio results.
    - Never invent values.
    - Never estimate missing information.
    - If information is unavailable, explicitly state "Not Available".
    - Use only the supplied portfolio dictionaries.

    Formatting Rules:

    1. Do NOT use Markdown.
    2. Do NOT use #, ##, ### headings.
    3. Do NOT use **bold**, *, -, or Markdown tables.
    4. Do NOT use emojis.
    5. Do NOT use long paragraphs.
    6. Keep each point concise (1-2 sentences maximum).
    7. Every section must contain numbered points.

    For any portfolio metrics, always refer to them using their exact dictionary key names.

    Example:

    portfolio_return
    portfolio_volatility
    execution_time
    cash_remaining
    total_transaction_cost

    Do not rename these keys.

    Structure the report exactly in the following order:

    Overall Summary

    1.
    2.
    3.
    4.

    Classical Portfolio Summary

    1.
    2.
    3.
    4.

    Quantum Portfolio Summary

    1.
    2.
    3.
    4.

    Comparison

    1.
    2.
    3.
    4.
    5.

    Key Insights

    1.
    2.
    3.
    4.
    5.

    AI Recommendations

    1.
    2.
    3.
    4.

    Final Conclusion

    1.
    2.

    Important Rules

    - Mention dictionary key names exactly whenever discussing values.
    - Do not generate tables.
    - Do not generate Markdown.
    - Do not generate bullet symbols.
    - Use only numbered lists.
    - Do not repeat the same information.
    - Keep the report professional and suitable for direct insertion into a PDF.
    """

    user_prompt = f"""
    Classical Portfolio
    -------------------
    {classical_optimization_results}

    Quantum Portfolio
    -----------------
    {quantum_optimization_results}

    User Question
    -------------
    {question}
    """

    response = client.models.generate_content(
    model="gemini-2.5-flash",
    contents=[user_prompt,system_prompt]
    )

    return response.text

def ai_copilot():

    if "copilot_open" not in st.session_state:
        st.session_state.copilot_open = False

    if "messages" not in st.session_state:
        st.session_state.messages = []

    # -----------------------
    # Toggle Button
    # -----------------------

    st.markdown(
        """
        <style>

        .toggle-btn{
            position:fixed;
            top:90px;
            right:20px;
            z-index:999999;
        }

        </style>
        """,
        unsafe_allow_html=True,
    )

    col1, col2 = st.columns([8, 1])

    with col2:

        if st.button("🤖 AI"):
            st.session_state.copilot_open = (
                not st.session_state.copilot_open
            )

    # -----------------------
    # Chat Window
    # -----------------------

    if st.session_state.copilot_open:

        st.markdown(
            '<div class="chat-panel">',
            unsafe_allow_html=True,
        )

        st.header("🤖 AI Copilot")

        st.divider()

        for msg in st.session_state.messages:

            with st.chat_message(msg["role"]):

                st.write(msg["content"])


        if "latest_summary" in st.session_state:

            summary = st.session_state["latest_summary"]
            pdf = generate_pdf(
                st.session_state["latest_summary"],
                classical_optimization_results,
                quantum_optimization_results
            )

            st.download_button(

                "📄 Download PDF Report",

                pdf,

                "Portfolio_Report.pdf",

                "application/pdf"

            )

        question = st.chat_input("Ask anything...")

        if question:

            st.session_state.messages.append(
                {
                    "role": "user",
                    "content": question
                }
            )
            loading_messages = [
                "📈 Calculating portfolio metrics...",
                "⚛️ Running quantum analysis...",
                "📊 Comparing classical and quantum results...",
                "💡 Generating AI recommendations...",
                "🔍 Evaluating portfolio performance..."
            ]

            with st.spinner(random.choice(loading_messages)):
                answer = portfolio_copilot(
                    question,
                    classical_optimization_results,
                    quantum_optimization_results
                )
            st.session_state["latest_summary"] = answer
            st.session_state.messages.append(
                {
                    "role": "assistant",
                    "content": answer
                }
            )

            st.rerun()

        st.markdown(
            "</div>",
            unsafe_allow_html=True,
        )


